<?php
/**
 * WhatsappPhoneNumberNameStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YCloud API
 *
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YCloud\Client\Model;
use \YCloud\Client\ObjectSerializer;

/**
 * WhatsappPhoneNumberNameStatus Class Doc Comment
 *
 * @category Class
 * @description The review status of the current display name request. See also [Get Display Name Status](https://developers.facebook.com/docs/whatsapp/business-management-api/manage-phone-numbers#get-display-name-status--beta-). - &#x60;APPROVED&#x60;: The name has been approved. You can download your certificate now. - &#x60;AVAILABLE_WITHOUT_REVIEW&#x60;: The certificate for the phone is available and display name is ready to use without review. - &#x60;DECLINED&#x60;: The name has not been approved. You cannot download your certificate. - &#x60;EXPIRED&#x60;: Your certificate has expire and can no longer be downloaded. - &#x60;PENDING_REVIEW&#x60;: Your name request is under review. You cannot download your certificate. - &#x60;NONE&#x60;: No certificate is available.
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhatsappPhoneNumberNameStatus
{
    /**
     * Possible values of this enum
     */
    public const APPROVED = 'APPROVED';

    public const AVAILABLE_WITHOUT_REVIEW = 'AVAILABLE_WITHOUT_REVIEW';

    public const DECLINED = 'DECLINED';

    public const EXPIRED = 'EXPIRED';

    public const PENDING_REVIEW = 'PENDING_REVIEW';

    public const NONE = 'NONE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPROVED,
            self::AVAILABLE_WITHOUT_REVIEW,
            self::DECLINED,
            self::EXPIRED,
            self::PENDING_REVIEW,
            self::NONE
        ];
    }
}


