<?php
/**
 * WhatsappTemplateSubCategory
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YCloud API
 *
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YCloud\Client\Model;
use \YCloud\Client\ObjectSerializer;

/**
 * WhatsappTemplateSubCategory Class Doc Comment
 *
 * @category Class
 * @description Subcategory of WhatsApp templates. - ORDER_STATUS: Order status template is categorized as &#x60;UTILITY&#x60; template and apart from name and language of choice, it has general template components such as &#x60;BODY&#x60;, &#x60;FOOTER&#x60; and additionally subcategory as &#x60;ORDER_STATUS&#x60;.
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhatsappTemplateSubCategory
{
    /**
     * Possible values of this enum
     */
    public const ORDER_STATUS = 'ORDER_STATUS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER_STATUS
        ];
    }
}


