<?php
/**
 * WhatsappTemplateComponentButtonType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YCloud API
 *
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YCloud\Client\Model;
use \YCloud\Client\ObjectSerializer;

/**
 * WhatsappTemplateComponentButtonType Class Doc Comment
 *
 * @category Class
 * @description Button type. - &#x60;PHONE_NUMBER&#x60;: Phone number buttons call the specified business phone number when tapped by the app user. Templates are limited to one phone number button. - &#x60;URL&#x60;: URL buttons load the specified URL in the device&#39;s default web browser when tapped by the app user. Templates are limited to two URL buttons. - &#x60;QUICK_REPLY&#x60;: Quick reply buttons are custom text-only buttons that immediately message you with the specified text string when tapped by the app user. Templates are limited to 10 quick reply buttons. If using quick reply buttons with other buttons, buttons must be organized into two groups: quick reply buttons and non-quick reply buttons. - &#x60;COPY_CODE&#x60;: Copy code buttons copy a text string (defined when the template is sent in a template message) to the device&#39;s clipboard when tapped by the app user. Templates are limited to one copy code button. - &#x60;OTP&#x60;: One-time password (OTP) buttons are a special type of URL button component used with authentication templates. - &#x60;CATALOG&#x60;: When a customer taps the **View catalog** button in a catalog template message, your product catalog appears within WhatsApp. - &#x60;MPM&#x60;: Customers can browse products and sections by tapping the **View items** button in a multi-product template message. - &#x60;FLOW&#x60;: Use this type to specify the [Flow](https://developers.facebook.com/docs/whatsapp/flows) to be sent with the template message. - &#x60;ORDER_DETAILS&#x60;: Provides a order details button with &#x60;Review and Pay&#x60; text. - &#x60;VOICE_CALL&#x60;: Triggers a WhatsApp call, when clicked by a WhatsApp customer.
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhatsappTemplateComponentButtonType
{
    /**
     * Possible values of this enum
     */
    public const PHONE_NUMBER = 'PHONE_NUMBER';

    public const URL = 'URL';

    public const QUICK_REPLY = 'QUICK_REPLY';

    public const COPY_CODE = 'COPY_CODE';

    public const OTP = 'OTP';

    public const CATALOG = 'CATALOG';

    public const MPM = 'MPM';

    public const FLOW = 'FLOW';

    public const ORDER_DETAILS = 'ORDER_DETAILS';

    public const VOICE_CALL = 'VOICE_CALL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PHONE_NUMBER,
            self::URL,
            self::QUICK_REPLY,
            self::COPY_CODE,
            self::OTP,
            self::CATALOG,
            self::MPM,
            self::FLOW,
            self::ORDER_DETAILS,
            self::VOICE_CALL
        ];
    }
}


