<?php
/**
 * WhatsappTemplateStatusUpdateEventEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YCloud API
 *
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YCloud\Client\Model;
use \YCloud\Client\ObjectSerializer;

/**
 * WhatsappTemplateStatusUpdateEventEnum Class Doc Comment
 *
 * @category Class
 * @description Used when an event happened on WhatsApp template status updates.
 * @package  YCloud\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhatsappTemplateStatusUpdateEventEnum
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'PENDING';

    public const APPROVED = 'APPROVED';

    public const REJECTED = 'REJECTED';

    public const IN_APPEAL = 'IN_APPEAL';

    public const PAUSED = 'PAUSED';

    public const FLAGGED = 'FLAGGED';

    public const DISABLED = 'DISABLED';

    public const REINSTATED = 'REINSTATED';

    public const PENDING_DELETION = 'PENDING_DELETION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::APPROVED,
            self::REJECTED,
            self::IN_APPEAL,
            self::PAUSED,
            self::FLAGGED,
            self::DISABLED,
            self::REINSTATED,
            self::PENDING_DELETION
        ];
    }
}


